name: Scrape Jugantor Editorial News

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml
        
    - name: Run scraper
      run: |
        python scraper.py
        
    - name: Check if XML file was created
      run: |
        if [ -f editorial_news.xml ]; then
          echo "✓ XML file created successfully"
          ls -lh editorial_news.xml
        else
          echo "✗ XML file not found!"
          exit 1
        fi
        
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update editorial news - $(date '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        fi 
